apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p6tx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p6tx
    app.kubernetes.io/part-of: ci1t-830-0031-app
  name: devfile-sample-p6tx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p6tx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p6tx
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0031-tenant/ci1t-830-0031-app/devfile-sample-p6tx@sha256:8a82d8c9d211a5245cde362ff418f4f9ea14f5b2249e9aaa9b482ecead8482a9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
